<?php

namespace Riaf\Bundle\AnondBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * @return Doctrine\ORM\Query
     */
    public function getQueryAll()
    {
        $qb = $this->createQueryBuilder('p')
            ->where('p.deletedAt IS NULL')
            ->orderBy('p.id', 'DESC')
        ;

        return $qb->getQuery();
    }
}
